# Generated by Django 3.0.8 on 2020-07-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200721_2223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='name',
            new_name='Name',
        ),
        migrations.AddField(
            model_name='order_item',
            name='price',
            field=models.IntegerField(default=1),
        ),
    ]
