# Generated by Django 3.0.8 on 2020-07-21 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200721_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_item',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order_item',
            name='order',
        ),
        migrations.RemoveField(
            model_name='order_item',
            name='product_id',
        ),
        migrations.DeleteModel(
            name='order',
        ),
        migrations.DeleteModel(
            name='order_item',
        ),
    ]
